# This file stores configurations for your Shopify app.

scopes = "write_products,read_checkouts,write_checkouts,read_customer_merge,write_customer_merge,read_customers,write_customers,read_draft_orders,write_draft_orders,read_orders,write_orders"
  